# Configs for Just Guns

## Game Config

### Players

minPlayers: 2
maxPlayers: 10

# in seconds.
respawnTime: 5

### Points

winPoints: 50
deathPoints: 10


## Gun Configs

### Default
defaultDmg: 1
defaultRange: 1
maxDmg: 5
maxRange: 3

### Upgrades
baseDmgCost: 100
dmgUpgradeMultiplier: 5
baseRangeCost: 50
rangeUpgradeMultiplier: 3

### Multipliers

rangeMultiplier: 20